# fly.toml app configuration file generated for lun-log-shipper on 2023-09-14T11:17:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lun-log-shipper"
primary_region = "fra"

[http_service]
internal_port = 8686
auto_stop_machines = false
auto_start_machines = false

[metrics]
port = 9598
path = "/metrics"

[checks]
[checks.health]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"
port = 8686
type = "http"
