[transforms.datadog_remap]
type = "remap"
inputs = ["datadog_filter"]
source = '''
  .fly.app.name = string!(.fly.app.name)
  .service = replace(.fly.app.name, "-stage", "")
  if .service == "lun-backend" {
    .ddsource = "go"
  }
  if .service == "lun-kelvin" {
    .ddsource = "typescript"
  }
  .hostname = .fly.host
'''

[transforms.datadog_filter]
type = "filter"
inputs = ["log_json"]
#condition = { type = "vrl", source = ".fly.app.name == \"lun-backend\" || .fly.app.name == \"lun-backend-stage\"" }
## No builders
condition = { type = "vrl", source = "!starts_with(to_string!(.fly.app.name), \"fly-builder\")" }

[sinks.datadog]
# General
type = "datadog_logs"                   # required
inputs = ["datadog_remap"]              # required
default_api_key = "${DATADOG_API_KEY}"  # required
site = "${DATADOG_SITE:-datadoghq.com}" # optional
compression = "gzip"                    # optional, default

# Healthcheck
healthcheck.enabled = true # optional, default
